name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run-app
        working-directory: build
        run: ./app -i ../instances/sample.txt -s CAUSAL_PIBT_MAPF -v

      - name: build-visualizer
        working-directory: visualizer
        run: |
          sh ../openFrameworks/scripts/osx/download_libs.sh
          make build
