name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: build
        run: |
          ls -all
          mkdir build
          cd build
          cmake ..
          make

      - name: run-app
        working-directory: build
        run: ./app -i ../instances/sample.txt -s CAUSAL_PIBT_MAPF -v
